# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.2"
  config.vm.network :private_network, ip: "RFC参照"

  config.vm.provider :virtualbox do |vb|
    vb.customize [
      "modifyvm", :id,
      "--memory", 2048,
      "--cpus", 1
    ]
  end

  config.vm.provision :shell, path: 'setting/provision.sh'
end
